services:
  cryptext-backend:
    build:
      context: .
    container_name: cryptext-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
